# Generated by Django 4.0.6 on 2022-07-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_tag_options_rename_title_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(to='blog.tag'),
        ),
    ]
