# Generated by Django 4.0.6 on 2022-07-21 14:36

from django.db import migrations
from apps.blog.models import BlogCategory


def add_blog_categories(apps, schema_editor):
    categories = [
        'Новости',
        'Обзор'
        'Акция',
        'Партнерам',
        'Специальное предложение',
    ]
    for category in categories:
        BlogCategory.objects.create(title=category)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_publications'),
    ]

    operations = [
        migrations.RunPython(add_blog_categories)
    ]
